Repository googleapis/gax-nodejs, pull requests merged in 2019-07, with the labels that each got.

#528 Prettify browser branch
  browser-test/fixtures/echo.json
  browser-test/fixtures/echoProtoJson.ts
  browser-test/test.grpc.ts
  package.json
  src/browser.ts
  src/bundlingCalls/bundleExecutor.ts
  src/longRunningCalls/longrunning.ts
  src/operationsClientBrowser.ts
  tsconfig.json
Labels: cla: yes

#529 fix: copy values from LRO to Operation wrapper
  src/longRunningCalls/longrunning.ts
  test/longrunning.ts
Labels: cla: yes

#530 chore: release 1.1.4
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#532 chore(deps): update dependency @grpc/grpc-js to ^0.5.2
  package.json
Labels: cla: yes

#533 chore: release 1.1.5
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#535 Added more tests
  browser-test/fixtures/echo_client.js
  browser-test/fixtures/echo_client_config.json
  browser-test/fixtures/mock-server.js
  browser-test/test.endtoend.ts
  browser-test/test.grpc.ts
  browser-test/test.mockendtoend.ts
  karma.conf.js
  package.json
  src/browser.ts
  src/grpc.ts
Labels: cla: yes

#536 Renamed references to LangaugeService
  src/browser.ts
Labels: cla: yes

#539 Changed end-to-end tests so that tests only run after server is up and running
  browser-test/echoProtoJson.ts
  browser-test/test.endtoend.ts
  src/browser.ts
  src/operationsClientBrowser.ts
Labels: cla: yes

#540 Minor fixes
  karma.conf.js
  src/browser.ts
  src/bundlingCalls/bundleExecutor.ts
  src/normalCalls/retries.ts
  src/operationsClientBrowser.ts
  tools/tsconfig.json
Labels: cla: yes

#541 docs: fix the url for codecov.io
  README.md
Labels: cla: yes

#542 More minor fixes
  browser-test/echoProtoJson.ts
  package.json
  pbjs-genfiles/README.md
  src/browser.ts
  src/operationsClientBrowser.ts
  src/streamingCalls/streamDescriptor.ts
Labels: cla: yes

#543 feat: allow to pass just one file path to loadProto
  src/grpc.ts
  test/grpc.ts
Labels: cla: yes

#544 feat: reexport protobufjs from gax
  src/index.ts
  test/grpc.ts
Labels: cla: yes

#553 Adding JSDoc Documentation
  src/browser.ts
  src/grpc.ts
  src/operationsClient.ts
  src/operationsClientBrowser.ts
Labels: cla: yes

#547 feat: compileProtos bin script
  .gitignore
  package.json
  test/compileProtos.ts
  test/fixtures/protoLists/nestedDir/test2_proto_list.json
  test/fixtures/protoLists/test1_proto_list.json
  tools/compileProtos.ts
Labels: cla: yes

#546 chore: release 1.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#555 fix: compileProtos should not fail if no protos are given
  test/compileProtos.ts
  test/fixtures/protoLists/empty/README.txt
  tools/compileProtos.ts
Labels: cla: yes

#556 chore: release 1.2.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#557 docs: use the jsdoc-fresh theme
  .jsdoc.js
Labels: cla: yes

#561 docs: document apiEndpoint over servicePath
  system-test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.js
Labels: cla: yes
