Repository googleapis/gax-nodejs, pull requests merged in 2019-02, with the labels that each got.

#404 docs: fix type for retryCodes
  src/gax.ts
Labels: cla: yes

#409 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#414 docs: update contributing guide
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes

#400 test: enable testing of grpc-js
  package.json
  src/grpc.ts
  system-test/system.ts
  test/grpc.ts
Labels: :rotating_light:, cla: yes

#417 chore: don't run system tests with grpc-js
  package.json
Labels: cla: yes

#418 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#419 Release google-gax v0.25.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#420 refactor: clean up operations client 🥬
  src/grpc.ts
  src/longrunning.ts
  src/operations_client.ts
  src/streaming.ts
Labels: cla: yes

#421 refactor: snake case savagery is for pythonistas 🙅‍♂️🐍
  package.json
  src/apiCallable.ts
  src/bundling.ts
  src/index.ts
  src/longrunning.ts
  src/operationsClient.ts
  src/pagedIteration.ts
  src/parserExtras.ts
  src/pathTemplate.ts
  src/pathTemplateParser.js
  src/pathTemplateParser.pegjs
  src/routingHeader.ts
  src/streaming.ts
  test/apiCallable.ts
  test/gax.ts
  test/longrunning.ts
  test/pagedIteration.ts
  test/pathTemplateParser.ts
  test/path_template.ts
  test/routingHeader.ts
  test/streaming.ts
  test/utils.ts
Labels: cla: yes

#423 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#425 test: do not use grpc-js in regular system test
  package.json
Labels: cla: yes

#426 fix: do not use console.warn or console.error
  src/bundling.ts
  src/isbrowser.ts
  src/streaming.ts
  src/warnings.ts
  test/warning.ts
  tsconfig.json
Labels: cla: yes

#424 fix: do not fail if bundledField is missing
  src/bundling.ts
  test/bundling.ts
Labels: cla: yes

#427 Release google-gax v0.25.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#422 refactor: cleanup unused files
  package.json
  src/auth.ts
  src/pagedIteration.ts
  test/.eslintrc.yml
  test/auth.ts
Labels: cla: yes

#429 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#428 build: use linkinator for docs test
  package.json
Labels: cla: yes

#433 chore(typescript): export common API call types
  src/index.ts
Labels: cla: yes

#434 fix: monitoring could be a common proto
  src/grpc.ts
Labels: cla: yes

#435 Release google-gax v0.25.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes
