Repository googleapis/gax-nodejs, pull requests merged in 2019-03, with the labels that each got.

#436 fix: do not hang in LRO forever if API returned nothing
  src/longrunning.ts
  test/longrunning.ts
Labels: cla: yes

#437 Release google-gax v0.25.4
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#440 build: update kokoro config
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#441 fix: includes @types/duplexify in package
  package.json
Labels: cla: yes

#443 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#444 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#451 test: longer timeout for Pub/Sub system tests
  system-test/system.ts
Labels: cla: yes

#450 Release google-gax v0.25.5
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#449 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#453 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#458 fix(ts): drop dependency on @types/duplexify
  package.json
  src/streaming.ts
Labels: cla: yes

#459 fix: bundling is optional in MethodConfig
  src/gax.ts
Labels: cla: yes

#460 Release google-gax v0.25.6
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
