Repository googleapis/gax-nodejs, pull requests merged in 2019-05, with the labels that each got.

#477 feat: do not use legacy grpc loadObject
  src/grpc.ts
Labels: cla: yes

#481 test: use npm pack instead of npm link
  system-test/test.clientlibs.ts
Labels: cla: yes

#478 Release google-gax v0.26.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes

#482 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#483 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#485 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#484 feat!: use @grpc/grpc-js instead of grpc
  .kokoro/test.bat
  README.md
  package.json
  src/bundlingCalls/bundleExecutor.ts
  src/bundlingCalls/task.ts
  src/call.ts
  src/gax.ts
  src/googleError.ts
  src/grpc.ts
  src/index.ts
  src/longRunningCalls/longrunning.ts
  src/normalCalls/retries.ts
  system-test/fixtures/google-gax-packaging-test-app/src/index.js
  system-test/test.clientlibs.ts
  test/apiCallable.ts
  test/bundling.ts
  test/grpc.ts
  test/longrunning.ts
Labels: cla: yes

#491 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#492 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#494 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#495 fix: DEADLINE_EXCEEDED retry code is idempotent
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#498 docs: mark lib as GA
  README.md
Labels: cla: yes

#502 add one more redirect to gh-pages
  Operation/index.html
Labels: cla: yes

#503 feat: allow loading multiple proto files at once
  src/grpc.ts
  test/grpc.ts
Labels: cla: yes

#504 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#506 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#508 fix: use latest proto-loader with fixed types
  package.json
  src/grpc.ts
Labels: cla: yes

#509 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: automerge, autorelease: pending, cla: yes, type: process

#514 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#513 docs: add configuration for doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  synth.metadata
Labels: cla: yes

#515 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
