Repository googleapis/gax-nodejs, pull requests merged in 2020-07, with the labels that each got.

#862 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#864 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#866 feat: properly decode error in fallback scenario, export FallbackServiceError type
  src/fallback.ts
  src/fallbackError.ts
  test/browser-test/test.grpc-fallback.ts
  test/unit/fallbackError.ts
  test/unit/grpc-fallback.ts
Labels: cla: yes

#868 feat: no protobuf dependency in generated js, d.ts
  src/fallback.ts
  src/index.ts
  test/unit/compileProtos.ts
  test/unit/exports.ts
  tools/compileProtos.ts
Labels: cla: yes

#872 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#871 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#877 chore: node8 kokoro configs
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none

#879 feat: add retryRequestOptions to call settings
  src/gax.ts
  src/streamingCalls/streaming.ts
  src/streamingCalls/streamingApiCaller.ts
Labels: cla: yes

#880 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#878 chore: add api-extractor.json, update kokoro configs
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#881 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#882 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#884 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
