Repository googleapis/gax-nodejs, pull requests merged in 2020-09, with the labels that each got.

#889 build: add Node 12 config
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: cloudbuild, automerge, cla: yes

#887 feat: emit 'response' with every page
  src/paginationCalls/pageDescriptor.ts
  test/unit/pagedIteration.ts
Labels: automerge, cla: yes

#893 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#898 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#903 fix: drop dependencies on lodash
  package.json
  src/bundlingCalls/bundlingUtils.ts
Labels: cla: yes

#896 fix: use timeout for idempotent API calls
  src/createApiCall.ts
  test/unit/apiCallable.ts
Labels: cla: yes

#900 fix(deps): bump node-fetch to ^2.6.1
  package.json
Labels: cla: yes

#906 refactor: have a static list of protos for grpc.ts
  package.json
  src/grpc.ts
  src/protosList.json
  tools/listProtos.ts
Labels: cla: yes

#907 fix(deps): drop semver dependency
  package.json
  src/grpc.ts
Labels: cla: yes

#901 fix: allow callOptions.retry settings with grpc streaming calls
  src/createApiCall.ts
  test/unit/streaming.ts
Labels: automerge, cla: yes

#911 docs: describing client library usage
  client-libraries.md
Labels: api: docs, automerge, cla: yes
