Repository googleapis/gax-nodejs, pull requests merged in 2020-06, with the labels that each got.

#841 feat: support proto3 optional fields in exported protos
  package.json
Labels: cla: yes

#839 feat: more information for exceed timeout error
  src/createApiCall.ts
  src/gax.ts
  src/normalCalls/retries.ts
  test/unit/apiCallable.ts
  test/unit/gax.ts
Labels: cla: yes

#840 fix: set default values for gRPC parameters
  src/grpc.ts
  test/unit/grpc.ts
Labels: cla: yes

#846 fix: remove version from protobuf unique root name
  test/fixtures/package.json
  test/unit/compileProtos.ts
  tools/compileProtos.ts
Labels: automerge, cla: yes

#847 chore: document the way to override bundling options
  src/gax.ts
Labels: automerge, cla: yes

#849 fix: segment in path template can contain wildcard
  src/pathTemplate.ts
  test/system-test/test.clientlibs.ts
  test/unit/pathTemplate.ts
Labels: automerge, cla: yes

#851 build: migrate to secret manager
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#853 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#855 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#856 fix(deps): use @grpc/grpc-js ~1.1.1
  package.json
  test/fixtures/google-gax-packaging-test-app/package.json
Labels: cla: yes

#860 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
