Repository googleapis/gax-nodejs, pull requests merged in 2020-03, with the labels that each got.

#739 build: update linkinator config
  linkinator.config.json
Labels: automerge, cla: yes

#740 build(tests): fix coveralls and enable build cop
  .github/workflows/ci.yaml
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
Labels: automerge, cla: yes

#743 fix(deps): use protobuf.js v6.8.9
  package.json
Labels: cla: yes

#744 feat: export bundle descriptor in descriptors interface
  src/index.ts
Labels: cla: yes

#748 feat!: throw for versions of Node.js older than v10.0.0
  .github/workflows/ci.yaml
  src/grpc.ts
Labels: cla: yes

#708 feat: support async iterator for paging method
  src/paginationCalls/pageDescriptor.ts
  test/fixtures/google-gax-packaging-test-app/src/index.js
  test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.js
  test/fixtures/google-gax-packaging-test-app/test/gapic-v1beta1.js
  test/unit/pagedIteration.ts
Labels: cla: yes

#754 feat: export ServiceError from @grpc/grpc-js
  src/index.ts
Labels: automerge, cla: yes

#735 fix(deps): use @grpc/grpc-js v0.7.2
  package.json
Labels: cla: yes, do not merge

#756 fix: allow passing numbers as path template parameters
  src/pathTemplate.ts
  test/unit/pathTemplate.ts
Labels: cla: yes

#753 chore: update github actions configuration
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes

#757 chore: use gts v2
  .eslintignore
  .eslintrc.json
  .eslintrc.yml
  .github/workflows/ci.yaml
  .prettierrc
  .prettierrc.js
  package.json
  samples/.eslintrc.yml
  src/bundlingCalls/bundleExecutor.ts
  src/bundlingCalls/bundlingUtils.ts
  src/bundlingCalls/task.ts
  src/call.ts
  src/fallback.ts
  src/fallbackError.ts
  src/gax.ts
  src/grpc.ts
  src/longRunningCalls/longRunningApiCaller.ts
  src/longRunningCalls/longRunningDescriptor.ts
  src/longRunningCalls/longrunning.ts
  src/operationsClient.ts
  src/paginationCalls/pageDescriptor.ts
  src/paginationCalls/pagedApiCaller.ts
  src/paginationCalls/resourceCollector.ts
  src/pathTemplate.ts
  src/pathTemplateParser.js
  src/streamingCalls/streaming.ts
  src/warnings.ts
  test/browser-test/test.endtoend.ts
  test/browser-test/test.grpc-fallback.ts
  test/browser-test/test.unit.ts
  test/fixtures/echoProtoJson.ts
  test/fixtures/google-gax-packaging-test-app/.eslintrc.yml
  test/fixtures/google-gax-packaging-test-app/.prettierrc
  test/fixtures/google-gax-packaging-test-app/src/index.js
  test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.js
  test/fixtures/google-gax-packaging-test-app/test/.eslintrc.yml
  test/fixtures/google-gax-packaging-test-app/test/gapic-v1beta1.js
  test/system-test/showcase-server.ts
  test/system-test/test.clientlibs.ts
  test/system-test/test.endtoend.ts
  test/unit/apiCallable.ts
  test/unit/bundling.ts
  test/unit/compileProtos.ts
  test/unit/gax.ts
  test/unit/grpc-fallback.ts
  test/unit/grpc.ts
  test/unit/longrunning.ts
  test/unit/pagedIteration.ts
  test/unit/pathTemplate.ts
  test/unit/pathTemplateParser.ts
  test/unit/routingHeader.ts
  test/unit/streaming.ts
  test/unit/warning.ts
  tools/compileProtos.ts
  tsconfig.json
  tslint.json
  webpack.config.js
Labels: cla: yes

#760 build: use TypeScript ^3.8.3, set lib to es2018
  package.json
  src/operationsClient.ts
  tsconfig.json
Labels: cla: yes

#759 chore!: require Node.js v10+
  package.json
Labels: cla: yes

#765 fix: make async iteration work for gRPC-fallback; refactor the code
  samples/package.json
  samples/pagination.js
  src/apitypes.ts
  src/paginationCalls/pageDescriptor.ts
  test/fixtures/google-gax-packaging-test-app/src/index.js
  test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.js
  test/unit/pagedIteration.ts
Labels: cla: yes
