Repository googleapis/gax-nodejs, pull requests merged in 2020-05, with the labels that each got.

#819 test: use built in assert
  package.json
  samples/package.json
  samples/system-test/test.pagination.js
  samples/system-test/test.quickstart.js
  test/browser-test/test.endtoend.ts
  test/browser-test/test.grpc-fallback.ts
  test/unit/apiCallable.ts
  test/unit/bundling.ts
  test/unit/gax.ts
  test/unit/grpc-fallback.ts
  test/unit/grpc.ts
  test/unit/longrunning.ts
  test/unit/pagedIteration.ts
  test/unit/pathTemplate.ts
  test/unit/pathTemplateParser.ts
  test/unit/routingHeader.ts
  test/unit/streaming.ts
  test/unit/utils.ts
  test/unit/warning.ts
Labels: cla: yes

#820 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#824 fix: new typescript, strict types
  test/unit/grpc.ts
  test/unit/pagedIteration.ts
Labels: cla: yes

#831 fix: typescript 3.9.3 compilation
  test/browser-test/test.grpc-fallback.ts
  test/unit/grpc-fallback.ts
Labels: automerge, cla: yes

#823 feat: parse path template using regexes
  package.json
  src/parserExtras.ts
  src/pathTemplate.ts
  src/pathTemplateParser.js
  src/pathTemplateParser.pegjs
  test/unit/pathTemplate.ts
  test/unit/pathTemplateParser.ts
Labels: cla: yes

#833 feat: support non-slash resource in path template
  src/pathTemplate.ts
  test/unit/pathTemplate.ts
Labels: cla: yes

#806 chore: drop dependency on through2
  package.json
  test/browser-test/test.unit.ts
  test/fixtures/google-gax-packaging-test-app/package.json
  test/fixtures/google-gax-packaging-test-app/test/gapic-v1beta1.js
  test/unit/pagedIteration.ts
  test/unit/streaming.ts
Labels: automerge, cla: yes

#834 fix: fix match logic for path template
  src/pathTemplate.ts
  test/unit/pagedIteration.ts
  test/unit/pathTemplate.ts
Labels: cla: yes
