Repository googleapis/gax-nodejs, pull requests merged in 2020-11, with the labels that each got.

#930 test: make tests work in Node 15
  .github/workflows/ci.yaml
  test/unit/grpc-fallback.ts
  test/unit/streaming.ts
Labels: automerge, cla: yes

#931 fix(deps): use google-auth-library with defaultScopes
  package.json
Labels: automerge, cla: yes

#926 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: docs, automerge, cla: yes, context: full

#933 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full
