Repository googleapis/gax-nodejs, pull requests merged in 2021-08, with the labels that each got.

#1057 feat: decode error details property from google.rpc.Status
  protos/status.json
  src/call.ts
  src/fallback.ts
  src/fallbackError.ts
  src/googleError.ts
  test/fixtures/multipleErrors.json
  test/unit/fallbackError.ts
  test/unit/googleError.ts
Labels: cla: yes

#1071 fix(deps): pin protobufjs
  package.json
Labels: automerge, cla: yes

#1072 chore(nodejs): update client ref docs link in metadata
  .repo-metadata.json
Labels: automerge, cla: yes

#1074 feat: use proto3 JSON serializer for REGAPIC workflows
  package.json
  src/fallback.ts
  src/fallbackProto.ts
  src/fallbackRest.ts
  src/fallbackServiceStub.ts
  src/index.ts
  src/transcoding.ts
  test/browser-test/test.endtoend.ts
  test/browser-test/test.grpc-fallback.ts
  test/browser-test/test.unit.ts
  test/fixtures/google-gax-packaging-test-app/src/index.js
  test/unit/grpc-fallback.ts
  test/unit/regapic.ts
  test/unit/transcoding.ts
Labels: cla: yes

#1077 fix: do not fail when decoding unknown error
  src/googleError.ts
  test/unit/googleError.ts
Labels: cla: yes, automerge

#1079 fix: refactor path templates to simplify regexes
  src/pathTemplate.ts
Labels: cla: yes

#1070 feat: promote ErrorInfo fields
  src/call.ts
  src/googleError.ts
  test/unit/googleError.ts
Labels: cla: yes, automerge

#1075 feat: GoogleError/GoogleErrorDecoder integration testing
  package.json
  test/fixtures/google-gax-packaging-test-app/src/index.js
Labels: cla: yes

#1085 fix(deps): upgrade google auth to 7.6.1
  package.json
Labels: cla: yes

#1087 fix: do not throw error on empty LRO response
  src/longRunningCalls/longrunning.ts
  test/unit/longrunning.ts
Labels: cla: yes, automerge

#1093 fix: use the full type name for ErrorInfo
  src/googleError.ts
Labels: cla: yes, kokoro:run
