Repository googleapis/gax-nodejs, pull requests merged in 2021-05, with the labels that each got.

#998 fix: prettier rules change
  src/bundlingCalls/bundleDescriptor.ts
  src/bundlingCalls/bundleExecutor.ts
  src/fallback.ts
  src/fallbackError.ts
  src/iamService.ts
  src/longRunningCalls/longrunning.ts
  src/operationsClient.ts
  src/paginationCalls/pageDescriptor.ts
  src/paginationCalls/pagedApiCaller.ts
  src/transcoding.ts
  test/browser-test/test.grpc-fallback.ts
  test/unit/bundling.ts
  test/unit/grpc.ts
  test/unit/iamService.ts
  test/unit/longrunning.ts
  test/unit/operationClient.ts
  test/unit/pagedIteration.ts
  test/unit/regapic.ts
  test/unit/transcoding.ts
Labels: automerge, cla: yes

#995 fix: do not consider inherited properties for transcoding
  src/transcoding.ts
  test/unit/transcoding.ts
Labels: automerge, cla: yes

#997 feat: add validation for proto3 optional default value
  src/fallback.ts
  src/transcoding.ts
  test/fixtures/fallback-default-value/test_optional.proto
  test/fixtures/fallbackOptional.ts
  test/fixtures/test-default-value.json
  test/unit/transcoding.ts
Labels: cla: yes

#1004 fix: load LRO proto JSON using require
  src/operationsClient.ts
Labels: cla: yes

#1003 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1005 feat: update rest version for metrics
  src/fallback.ts
Labels: cla: yes

#1007 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1010 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
Labels: cla: yes

#1009 feat: add type parameter to warn function
  package.json
  src/index.ts
  src/warnings.ts
  test/unit/warning.ts
Labels: cla: yes

#1015 fix: rest transport enum value display incorectly
  src/fallback.ts
  test/fixtures/google/example/library/v1/library.proto
  test/fixtures/library.json
  test/unit/regapic.ts
Labels: automerge, cla: yes
