Repository googleapis/gax-nodejs, pull requests merged in 2022-06, with the labels that each got.

#1276 feat: support regapic LRO
  src/fallback.ts
  src/grpc.ts
  src/operationsClient.ts
  src/transcoding.ts
  test/unit/streaming.ts
  test/unit/transcoding.ts
Labels: size: m

#1280 fix: update googlePRotoFilesDir
  src/grpc.ts
Labels: automerge, size: xs

#1284 docs: describe fallback REST option
  client-libraries.md
Labels: size: s
