Repository googleapis/gax-nodejs, pull requests merged in 2022-05, with the labels that each got.

#1242 fix: pin @grpc/proto-loader to v0.6.9
  package.json
Labels: size: xs

#1238 fix: handle rest stream callback is undefined
  src/fallbackServiceStub.ts
Labels: size: xs

#1248 fix: add development dependency long
  package.json
  test/unit/compileProtos.ts
  tools/compileProtos.ts
Labels: size: s

#1253 fix: upgrade proto-loader and add long dev dependency
  package.json
  protos/iam_service.d.ts
  protos/operations.d.ts
  test/fixtures/google-gax-packaging-test-app/protos/protos.d.ts
Labels: size: s

#1249 build!: reduce module size by remove duplicate storage for protos files
  package.json
  src/googleError.ts
  test/fixtures/google-gax-packaging-test-app/src/index.ts
Labels: automerge, size: xs

#1257 fix: revert gRPC stream change in #1226
  src/streamingCalls/streaming.ts
  test/fixtures/google-gax-packaging-test-app/src/v1beta1/echo_client.ts
  test/fixtures/google-gax-packaging-test-app/test/gapic-v1beta1.ts
Labels: size: s

#1252 build!: drop Node 10 to support and update lastest Typescript
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  package.json
  src/streamingCalls/streaming.ts
  test/browser-test/test.endtoend.ts
  test/browser-test/test.grpc-fallback.ts
  test/browser-test/test.unit.ts
  test/fixtures/google-gax-packaging-test-app/package.json
  test/fixtures/google-gax-packaging-test-app/src/index.ts
  test/unit/bundling.ts
  test/unit/gax.ts
  test/unit/googleError.ts
  test/unit/grpc-fallback.ts
  test/unit/grpc.ts
  test/unit/longrunning.ts
  test/unit/pagedIteration.ts
  test/unit/regapic.ts
  test/unit/streaming.ts
  test/unit/transcoding.ts
Labels: size: m

#1263 fix!: remove pageSize/pageToken from call settings
  src/gax.ts
  src/paginationCalls/pagedApiCaller.ts
  test/unit/pagedIteration.ts
Labels: size: s

#1265 fix: get protos from build/protos
  tools/compileProtos.ts
Labels: size: xs

#1273 fix: decode Http error using proto3-JSON-serializer
  src/fallbackServiceStub.ts
  src/googleError.ts
  src/streamArrayParser.ts
  test/unit/googleError.ts
  test/unit/grpc-fallback.ts
Labels: size: m

#1275 fix: parse error from stream call
  src/googleError.ts
  src/streamingCalls/streaming.ts
  test/unit/googleError.ts
  test/unit/streaming.ts
Labels: size: m
