Repository googleapis/gax-nodejs, pull requests merged in 2022-08, with the labels that each got.

#1311 fix: make browser and rest use case work
  src/createApiCall.ts
  src/fallback.ts
  src/fallbackRest.ts
  src/locationService.ts
Labels: size: m

#1313 fix: require long instead of import
  test/unit/compileProtos.ts
  tools/compileProtos.ts
Labels: automerge, size: s

#1299 fix: make sure we do not change casing for fields that are user inputs
  src/transcoding.ts
  test/fixtures/test-default-value.json
  test/unit/transcoding.ts
Labels: size: m

#1309 feat: add fallback logic in error handling
  src/googleError.ts
Labels: size: s

#1304 fix: return error if GetOperation call fails
  src/longRunningCalls/longrunning.ts
  test/unit/longrunning.ts
Labels: size: m

#1291 fix: return Google Error when there is a missing required parameter
  src/fallbackRest.ts
  src/fallbackServiceStub.ts
  src/transcoding.ts
  test/unit/transcoding.ts
Labels: size: m

#1316 chore(deps): remove @types/download from devDependencies
  package.json
  test/showcase-server/package.json
Labels: size: xs

#1317 fix: add linebreak after require in the generated file
  tools/compileProtos.ts
Labels: automerge, size: xs

#1324 fix(deps): set min version of node-fetch to 2.6.7
  package.json
Labels: size: xs

#1323 chore: make browser test required
  .github/sync-repo-settings.yaml
  owlbot.py
Labels: size: xs

#1320 fix: Use uppercase method name when use fetch api
  src/fallbackProto.ts
  src/fallbackRest.ts
  src/fallbackServiceStub.ts
Labels: automerge, size: s

#1326 feat: export protobuf separately, avoid loading gRPC unless needed
  src/fallback.ts
  src/iamService.ts
  src/locationService.ts
  src/operationsClient.ts
  src/protobuf.ts
  test/unit/compileProtos.ts
  tools/compileProtos.ts
Labels: size: m

#1331 fix: refactor createByteLengthFunction, warn if fails
  src/fallback.ts
  src/gax.ts
  src/grpc.ts
Labels: size: s
