Repository googleapis/gax-nodejs, pull requests merged in 2023-02, with the labels that each got.

#1414 fix: preserve existing query string parameters when adding enum encoding option
  src/fallbackRest.ts
  test/fixtures/google/example/library/v1/library.proto
  test/fixtures/library.json
  test/unit/regapic.ts
Labels: size: l

#1417 test: ignore RESOURCE_EXHAUSTED error for system tests
  test/system-test/test.clientlibs.ts
Labels: size: m

#1418 fix: get rid of fs-extra
  package.json
  test/system-test/test.clientlibs.ts
  test/unit/minify.ts
  tools/prepublish.ts
Labels: size: s

#1379 fix: include Long import in d.ts files
  protos/compute_operations.d.ts
  protos/locations.d.ts
Labels: automerge, size: xs
