Repository googleapis/gax-nodejs, pull requests merged in 2023-09, with the labels that each got.

#1459 feat: add ESM tools in gax
  tools/package.json
  tools/src/compileProtos.ts
  tools/src/replaceESMMockingLib.ts
  tools/src/replaceImportMetaUrl.ts
  tools/src/toggleESMFlagVariable.ts
  tools/test/compileProtos.ts
  tools/test/fixtures/esm/echo.js
  tools/test/fixtures/esm/echo.json
  tools/test/fixtures/esm/protoLists/empty/README.txt
  tools/test/fixtures/esm/protoLists/nestedDir/test2_proto_list.json
  tools/test/fixtures/esm/protoLists/test1_proto_list.json
  tools/test/replaceESMMockingLib.ts
  tools/test/replaceImportMetaUrl.ts
  tools/test/toggleESMFlagVariable.ts
  tools/tsconfig.json
Labels: automerge, size: xl

#1501 chore: update .release-please-manifest.json
  .release-please-manifest.json
Labels: size: xs

#1503 build: update release-please.yml
  .github/release-please.yml
  owlbot.py
Labels: size: xs

#1506 build: correct repository for publication failures
  gax/package.json
  tools/package.json
Labels: size: s
