Repository googleapis/gax-nodejs, pull requests merged in 2023-07, with the labels that each got.

#1470 fix: add missing devDependency for compodoc
  package.json
Labels: size: xs

#1467 fix: update protobufjs
  linkinator.config.json
  package.json
Labels: size: xs

#1472 test: run speech system tests from monorepo
  test/system-test/test.clientlibs.ts
Labels: size: s

#1001 fix: the return types for IAM service methods should be arrays, to match ReturnTuple
  src/iamService.ts
  src/protosList.json
  test/showcase-echo-client/src/v1beta1/echo_client.ts
  test/system-test/test.clientlibs.ts
Labels: cla: yes, size: s

#1475 Fix: `rimraf` version + remove conflicting types
  package.json
  test/showcase-server/package.json
  test/showcase-server/src/index.ts
  test/system-test/test.clientlibs.ts
  tools/package.json
  tools/test/compileProtos.ts
  tools/test/minify.ts
Labels: size: s

#1478 fix: update some pnpm deps
  package.json
  tools/package.json
Labels: size: xs

#1480 fix: make gapic-tools depend on gax-nodejs
  package.json
  tools/package.json
  tools/src/compileProtos.ts
  tools/test/compileProtos.ts
  tsconfig.json
Labels: size: s

#1483 chore: release new version of gapic-tools
  tools/package.json
Labels: size: xs
