Repository googleapis/gax-nodejs, pull requests merged in 2024-01, with the labels that each got.

#1532 fix(deps): update google-proto-files to include new field_info proto
  gax/package.json
Labels: size: xs

#1536 chore: update release-please-config.json to clean up release tags
  release-please-config.json
Labels: size: xs

#1533 fix(deps): update google-gax and google-proto-files
  tools/package.json
Labels: size: xs

#1541 chore: update release-please-config.json
  release-please-config.json
Labels: size: xs

#1542 feat: expose uuid for autopopulation of request_id
  gax/package.json
  gax/src/fallback.ts
  gax/src/index.ts
  gax/src/util.ts
  gax/test/unit/util.ts
Labels: size: s

#1547 fix: run update-protos to include new field_info.proto
  gax/src/protosList.json
Labels: size: xs

#1551 fix: do not throw DeprecationWarnings for legacy retry behavior
  gax/src/gax.ts
  gax/test/unit/streaming.ts
Labels: size: m

#1552 feat: implement support for Trusted Partner Cloud
  gax/src/clientInterface.ts
  gax/src/fallback.ts
  gax/src/grpc.ts
  gax/test/unit/grpc-fallback.ts
  gax/test/unit/grpc.ts
Labels: size: m
