Repository googleapis/gax-nodejs, pull requests merged in 2024-03, with the labels that each got.

#1567 fix: update publish.sh token
  .kokoro/publish.sh
Labels: size: xs

#1530 fix: improve package.json lookup for root name
  tools/package.json
  tools/src/compileProtos.ts
  tools/test/compileProtos.ts
Labels: automerge: exact, size: s

#1570 build: update publish.cfg to grab the correct key name
  .kokoro/release/publish.cfg
Labels: size: xs

#1573 fix(deps): upgrade google-proto-files to 4.2.0
  gax/package.json
Labels: size: xs

#1579 fix(deps): update google-proto-files and gax in gapic-tools
  tools/package.json
Labels: size: xs

#1578 fix: don't retry server streaming calls if retryCodes is the empty array
  gax/src/streamingCalls/streaming.ts
  gax/test/unit/streaming.ts
Labels: size: m
