Repository googleapis/gax-nodejs, pull requests merged in 2024-04, with the labels that each got.

#1576 fix: update minimum grpc-js to 1.10.3 to skip potentially problematic 1.10.2
  gax/package.json
Labels: automerge, size: xs

#1583 chore: Update showcase client
  gax/package.json
  gax/src/createApiCall.ts
  gax/test/browser-test/test/test.grpc-fallback.ts
  gax/test/showcase-echo-client/package.json
  gax/test/showcase-echo-client/protos/google/showcase/v1beta1/echo.proto
  gax/test/showcase-echo-client/src/v1beta1/echo_client.ts
  gax/test/showcase-echo-client/src/v1beta1/echo_client_config.json
  gax/test/showcase-echo-client/src/v1beta1/index.ts
  gax/test/showcase-echo-client/src/v1beta1/sequence_service_client.ts
  gax/test/showcase-echo-client/tsconfig.json
  gax/test/showcase-server/src/index.ts
  gax/test/unit/streaming.ts
Labels: size: l

#1587 chore: regenerate showcase client
  gax/test/showcase-echo-client/protos/google/showcase/v1beta1/echo.proto
  gax/test/showcase-echo-client/src/v1beta1/echo_client.ts
Labels: size: xs
