Repository googleapis/gax-nodejs, pull requests merged in 2024-08, with the labels that each got.

#1636 fix: reduce duplicate code in streaming retries and add a test
  gax/src/streamingCalls/streaming.ts
  gax/test/test-application/src/index.ts
Labels: size: m

#1638 chore(deps): Update minimum `node-fetch`
  gax/package.json
Labels: size: xs

#1639 fix: test application cleanup
  gax/test/test-application/src/index.ts
Labels: size: l

#1641 feat: Improve `AuthClient` Compatibility
  gax/package.json
  gax/src/clientInterface.ts
  gax/src/fallback.ts
  gax/src/grpc.ts
  gax/src/iamService.ts
  gax/src/operationsClient.ts
  gax/test/unit/regapic.ts
Labels: size: m

#1648 Revert "feat: Improve `AuthClient` Compatibility (#1641)"
  gax/src/clientInterface.ts
  gax/src/fallback.ts
  gax/src/grpc.ts
  gax/src/iamService.ts
  gax/src/operationsClient.ts
  gax/test/unit/regapic.ts
Labels: size: m
