Repository googleapis/gax-nodejs, pull requests merged in 2025-03, with the labels that each got.

#1712 chore: update release-please-config.json
  release-please-config.json
Labels: size: xs

#1716 build: another attempt at making the release CI work
  logging-utils/package.json
  logging-utils/samples/package.json
Labels: size: xs

#1719 fix: update gax dependency in gapic tools
  tools/package.json
Labels: size: xs

#1725 fix: bypass colour checks when in browsers (or other non-Node-compatible runtimes)
  logging-utils/src/colours.ts
Labels: automerge: exact, size: xs

#1729 feat!: correct wrong return type for listOperations in Operation Client
  gax/src/operationsClient.ts
  gax/test/showcase-echo-client/protos/google/showcase/v1beta1/echo.proto
  gax/test/showcase-echo-client/src/index.ts
  gax/test/showcase-echo-client/src/v1beta1/echo_client.ts
  gax/test/showcase-echo-client/src/v1beta1/index.ts
  gax/test/showcase-echo-client/src/v1beta1/sequence_service_client.ts
  gax/test/showcase-echo-client/tsconfig.json
  gax/test/unit/operationClient.ts
Labels: size: xl

#1734 fix: add missing export path for generator
  gax/package.json
Labels: size: xs
