Repository googleapis/gax-nodejs, pull requests merged in 2025-05, with the labels that each got.

#1748 ci: release-please.yml to tag pull request number
  .github/release-please.yml
Labels: size: xs

#1750 fix(deps): update protobuf.js
  gax/package.json
Labels: size: xs

#1755 feat: next release from main branch is 4.6.1
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#1756 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: size: m

#1758 chore: clean up 4.6.1 release
  .github/release-please.yml
  .github/sync-repo-settings.yaml
  gax/CHANGELOG.md
Labels: size: s

#1753 feat: expose a static method for cached loading of protos from JSON and update protobuf.js to 7.5.2
  gax/package.json
  gax/src/fallback.ts
  gax/src/index.ts
Labels: size: s

#1752 chore: regenerate showcase
  gax/test/browser-test/test/test.grpc-fallback.ts
  gax/test/showcase-echo-client/package.json
  gax/test/showcase-echo-client/protos/google/showcase/v1beta1/echo.proto
  gax/test/showcase-echo-client/protos/google/showcase/v1beta1/sequence.proto
  gax/test/showcase-echo-client/src/index.ts
  gax/test/showcase-echo-client/src/v1beta1/echo_client.ts
  gax/test/showcase-echo-client/src/v1beta1/echo_client_config.json
  gax/test/showcase-echo-client/src/v1beta1/sequence_service_client.ts
  gax/test/showcase-echo-client/tsconfig.json
  gax/test/showcase-server/src/index.ts
Labels: size: xl

#1749 fix: Always save the error
  gax/src/normalCalls/retries.ts
  gax/test/test-application/src/index.ts
Labels: size: m

#1751 feat: support custom/unknown error types
  gax/src/googleError.ts
  gax/test/unit/googleError.ts
Labels: size: m
