Repository googleapis/gax-nodejs, pull requests merged in 2025-02, with the labels that each got.

#1534 fix: enable keepAlive for HTTP requests
  gax/src/fallbackServiceStub.ts
Labels: size: s

#1632 feat: Add minifyJson param to request minified JSON responses when using the REST fallback
  gax/src/fallback.ts
  gax/src/fallbackRest.ts
  gax/src/fallbackServiceStub.ts
  gax/src/grpc.ts
  gax/test/unit/regapic.ts
Labels: size: m

#1633 fix!: parse from HTTP errors and prefer that as the cannonical error code when it is provided
  gax/src/googleError.ts
  gax/test/unit/googleError.ts
Labels: size: s

#1652 fix: bytes field should be typed as a Buffer
  tools/src/compileProtos.ts
  tools/test/compileProtos.ts
Labels: size: s

#1700 docs: update docstring for forwardEvents
  gax/src/streamingCalls/streaming.ts
Labels: size: xs

#1704 feat: allow users to turn on logging without the environment variable
  logging-utils/README.md
  logging-utils/package.json
  logging-utils/src/logging-utils.ts
  logging-utils/test/logging-utils.ts
Labels: size: m

#1702 feat!: Update `google-auth-library` to v10
  gax/package.json
  gax/src/fallback.ts
  gax/src/fallbackServiceStub.ts
  gax/src/grpc.ts
  gax/src/iamService.ts
  gax/src/index.ts
  gax/src/operationsClient.ts
  gax/test/browser-test/package.json
  gax/test/browser-test/test/test.endtoend.ts
  gax/test/browser-test/test/test.grpc-fallback.ts
  gax/test/browser-test/webpack.config.js
  gax/test/test-application/src/index.ts
  gax/test/unit/grpc-fallback.ts
  gax/test/unit/grpc.ts
  gax/test/unit/regapic.ts
Labels: size: l

#1707 tests: move npm link around to try to fix dependency loop
  logging-utils/package.json
  logging-utils/samples/package.json
Labels: size: xs
