Repository googleapis/gax-nodejs, pull requests merged in 2025-06, with the labels that each got.

#1765 feat: export utils functions in gax
  gax/src/index.ts
Labels: size: xs

#1767 test: Fix `async`test issues
  gax/test/unit/apiCallable.ts
  gax/test/unit/bundling.ts
  gax/test/unit/iamService.ts
  gax/test/unit/locationService.ts
  gax/test/unit/longrunning.ts
  gax/test/unit/operationClient.ts
  gax/test/unit/pagedIteration.ts
Labels: size: l

#1771 build: re add minification tests
  gax/test/unit/regapic.ts
Labels: size: m

#1736 fix!: allow 204 responses in REST fallback mode
  gax/src/fallbackServiceStub.ts
  gax/test/unit/grpc-fallback.ts
  gax/test/unit/grpc.ts
  gax/test/unit/regapic.ts
Labels: size: m

#1773 fix(deps): update auth to 10.1.0
  gax/package.json
Labels: size: xs

#1738 chore(deps): Remove deprecated dependency @types/long
  gax/package.json
Labels: size: xs
